/** Centralized React Query cache keys — one source of truth per resource. */
export const queryKeys = {
  me: ["me"] as const,
  resumes: ["resumes"] as const,
  resume: (id: string) => ["resumes", id] as const,
  analysis: (resumeId: string) => ["analysis", resumeId] as const,
  analysisSummary: (resumeId: string) => ["analysis", resumeId, "summary"] as const,
  analysisSkills: (resumeId: string) => ["analysis", resumeId, "skills"] as const,
  analysisKeywords: (resumeId: string) => ["analysis", resumeId, "keywords"] as const,
  analysisHistory: (resumeId: string) => ["analysis", resumeId, "history"] as const,
  jobAnalysisHistory: ["job-analysis", "history"] as const,
  jobAnalysis: (id: string) => ["job-analysis", id] as const,
  jobAnalysisMatchedSkills: (id: string) => ["job-analysis", id, "matched-skills"] as const,
  jobAnalysisMissingSkills: (id: string) => ["job-analysis", id, "missing-skills"] as const,
  jobAnalysisKeywords: (id: string) => ["job-analysis", id, "keywords"] as const,
  tailoringHistory: ["tailoring", "history"] as const,
  tailoringSession: (id: string) => ["tailoring", id] as const,
  tailoringResume: (id: string) => ["tailoring", id, "resume"] as const,
  tailoringCoverLetter: (id: string) => ["tailoring", id, "cover-letter"] as const,
  conversations: ["chat", "conversations"] as const,
  conversation: (id: string) => ["chat", "conversations", id] as const,
  messages: (id: string) => ["chat", "conversations", id, "messages"] as const,
  dashboard: ["dashboard"] as const,
  dashboardTrends: (points: number) => ["dashboard", "trends", points] as const,
  notifications: (filters: Record<string, unknown>) => ["notifications", filters] as const,
  unreadCount: ["notifications", "unread-count"] as const,
};
